apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnk6MzAwMDEiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiTmV0YXBwMSEiLCJhdXRoIjoiWVdSdGFXNDZUbVYwWVhCd01TRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: reg-cred-secret
  namespace: gateway-system
type: kubernetes.io/dockerconfigjson