apiVersion: v1
kind: ServiceAccount
# Added for local privat docker registry
imagePullSecrets:
- name: reg-cred-secret
# End of Add
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github.com_NetApp-Learning-Services_gateway
    app.kubernetes.io/part-of: github.com_NetApp-Learning-Services_gateway
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
