# permissions for end users to edit storagevirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storagevirtualmachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: https://github.com/NetApp-Learning-Services/gateway
    app.kubernetes.io/part-of: https://github.com/NetApp-Learning-Services/gateway
    app.kubernetes.io/managed-by: kustomize
  name: storagevirtualmachine-editor-role
rules:
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines/status
  verbs:
  - get
