# permissions for end users to view storagevirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storagevirtualmachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github.com_NetApp-Learning-Services_gateway
    app.kubernetes.io/part-of: github.com_NetApp-Learning-Services_gateway
    app.kubernetes.io/managed-by: kustomize
  name: storagevirtualmachine-viewer-role
rules:
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines/status
  verbs:
  - get
