# permissions for end users to edit storagevirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagevirtualmachine-editor-role
rules:
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.netapp.com
  resources:
  - storagevirtualmachines/status
  verbs:
  - get
