## Append samples of your project ##
resources:
- gateway_v1alpha1_storagevirtualmachine.yaml
- gateway_v1alpha2_storagevirtualmachine.yaml
- gateway_v1alpha3_storagevirtualmachine.yaml
- gateway_v1beta1_storagevirtualmachine.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
