apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: v1
kind: Secret
metadata:
  name: ontap-svm-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: gateway.netapp.com/v1alpha1
kind: StorageVirtualMachine
metadata:
  name: storagevirtualmachine-sample
  namespace: gateway-system
spec:
  svmName: testVs
  clusterHost: 192.168.0.102
  debug: true
  management:
    name: manage1
    ip: 192.168.0.30
    netmask: 255.255.255.0
    broadcastDomain: Default
    homeNode: Cluster2-01
  vsadminCredentials:
    name: ontap-svm-admin
    namespace: gateway-system 
  clusterCredentials:
    name: ontap-cluster-admin
    namespace: gateway-system
  nfs:
    enabled: true
    v3: true
    v4: true
    v41: true
    interfaces:
    - name: nfs1
      ip: 192.168.0.30
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
    rules:
    - client: 0.0.0.0/0
      protocol: any
      rw: any
      ro: any
      superuser: any
      anon: 65534
