apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: v1
kind: Secret
metadata:
  name: ontap-svm-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: gateway.netapp.com/v1beta1
kind: StorageVirtualMachine
metadata:
  name: storagevirtualmachine-testcase
  namespace: gateway-system
spec:
  svmName: testVs
  clusterHost: 192.168.0.102
  debug: false
  aggregates:
  - name: Cluster2_01_FC_1
  management:
    name: manage1
    ip: 192.168.0.30
    netmask: 255.255.255.0
    broadcastDomain: Default
    homeNode: Cluster2-01
  vsadminCredentials:
    name: ontap-svm-admin
    namespace: gateway-system 
  clusterCredentials:
    name: ontap-cluster-admin
    namespace: gateway-system
  iscsi:
    enabled: true
    alias: testVs
    interfaces:
    - name: iscsi1
      ip: 192.168.0.32
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
    - name: iscsi2
      ip: 192.168.0.33
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
  nfs:
    enabled: true
    v3: true
    v4: true
    v41: true
    interfaces:
    - name: nfs1
      ip: 192.168.0.31
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
    export:
      name: default
      #simplified rules 
      rules:
      - clients: 0.0.0.0/0
        protocols: any
        rw: any
        ro: any
        superuser: any
        anon:  "65534"
      #but rules should look like this:
      # rules:
      # - clients: 
      #   - Match: 0.0.0.0/0
      #   protocols: 
      #   - any
      #   rw: 
      #   - any
      #   ro: 
      #   - any
      #   superuser: 
      #   - any
      #   anon: "65534"
