apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: v1
kind: Secret
metadata:
  name: ontap-test-vsadmin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: gateway.netapp.com/v1alpha1
kind: StorageVirtualMachine
metadata:
  name: storagevirtualmachine-sample
  namespace:  gateway-system
spec:
  svmName: testVs2
  clusterHost: 192.168.0.102
  management:
    name: lif1
    ip: 192.168.0.30
    netmask: 255.255.255.0
    broadcastDomain: Default
    homeNode: Cluster2-01
  vsadminCredentials:
    name: ontap-test-vsadmin
    namespace:   gateway-system 
  clusterCredentials:
    name: ontap-cluster-admin
    namespace:   gateway-system